# Generated by Django 4.2.15 on 2024-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0004_account_interest_rate_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the user has verified their email address.'),
        ),
    ]
