# Generated by Django 4.2.15 on 2024-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed 2FA setup.'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_key',
            field=models.CharField(blank=True, help_text='TOTP secret key for 2FA.', max_length=32, null=True),
        ),
    ]
