# Generated by Django 4.2.15 on 2024-08-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0006_user_is_2fa_verified_user_totp_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
    ]
