# Generated by Django 4.2.15 on 2024-08-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0007_remove_account_interest_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_2fa_verified',
            new_name='is_2fa_setup_completed',
        ),
    ]
