# Generated by Django 4.2.15 on 2024-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0008_rename_is_2fa_verified_user_is_2fa_setup_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer')], max_length=10),
        ),
    ]
